//! Library façade exposing all public modules for integration tests and `cargo doc`.

pub mod animation;
pub mod audio_reactive;
pub mod config;
pub mod error;
pub mod events;
pub mod field;
pub mod finance_driver;
pub mod gallery;
pub mod geodesic;
pub mod interactive;
pub mod lod;
#[cfg(feature = "lua")]
pub mod lua_surface;
pub mod morph;
pub mod multi_monitor;
pub mod palette;
pub mod parameter_tuner;
pub mod particles;
pub mod recorder;
pub mod renderer;
pub mod scene_presets;
pub mod surface;
pub mod symmetry;
pub mod trail;
pub mod tray;
pub mod wallpaper;
pub mod reaction_diffusion;
pub mod flow;
pub mod timelapse;
pub mod gradient;
pub mod preview;
pub mod tiling;
pub mod fractal;
pub mod composer;
pub mod noise;
